### PR TITLE
replaced NImageFetchViewDelegate with closures. Closes #7

### LINKED ISSUE #7: Change NImageFetchViewDelegate for a completion
We must refactor NImageFetchView to use a completion instead this protocol:

```swift
@protocol NImageFetchViewDelegate <NSObject>

@optional

/** Called when the requested image has been loaded and set on the image view */
- (void)imageViewDidSetRequestedImage:(NImageFetchView*)imageView;

/** Called if the image request failed */
- (void)imageView:(NImageFetchView*)imageView requestFailedWithError:(NSError*)error;

@end
```

### PR DESCRIPTION
**Pull request by albertopeam**
* removed NImageFetchViewDelegate and replaced by NImageFetchViewCompletion block
* added Swift Concurrency APIs to requestImage

### CODE REVIEW

**Comment by albertopeam** [comment]
I am having 2nd thoughts about concurrency APIs, probably using two threads and kind of a waste... I have to take a look

**Comment by albertopeam** [comment]
removed Swift Concurrency @albertocsouto

**Comment by albertocsouto** [comment]
Thanks! Great contribution, this closes #7. I added a simple test for the new feature, if you are ok with that we can merge

**Review by albertocsouto — APPROVED** [review]

**Comment by albertopeam** [comment]
As it is part of a UIView I didn't consider to do unit testing but better to have it, thanks @albertocsouto

**Comment by albertopeam** [comment]
@albertocsouto I am used to squash when merging features, if you prefer another strategy comment please :)

**Comment by albertocsouto** [comment]
Thanks! Squash is he prefered way

**Pull request merged**
